# Generated by Django 5.0.1 on 2024-05-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
